language: cpp
compiler: gcc
sudo: require
dist: xenial

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-xenial -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt510base libgl1-mesa-dev subversion libgphoto2-dev
  - source /opt/qt*/bin/qt*-env.sh

script:
  - svn checkout https://svn.code.sf.net/p/eos-movrec/code/trunk eos-movrec-code
  - cd eos-movrec-code
  - cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  - make -j$(nproc)
  - make DESTDIR=appdir -j$(nproc) install
  - mkdir -p appdir/usr/share/icons/hicolor/256x256/apps # FIXME: "make install" should do this
  - cp ./mac.icons/256.png appdir/usr/share/icons/hicolor/256x256/apps/eos-movrec.png # FIXME: "make install" should do this
  - mkdir -p appdir/usr/share/applications # FIXME: "make install" should do this
  - cp ../eos-movrec.desktop appdir/usr/share/applications/ # FIXME: "make install" should do this
  - find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh EOS*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
